### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/ExtendedDateTimeFormat#1]
Assuming that fd5c2e8cb5e477cba7f319591cb152e1fb2b76ad is stable, lets add a tag to manage dependencies in our other projects more easily.

Since this is coming from our SVN repository, not sure what tag name we want to give this. 1.0.0? Suggestions?

**Comment by lauren-unt** [comment]
Your suggestion sounds fine to me.
________________________________________

**Comment by damonkelley** [comment]
Tagged as `1.0.0`
